[package]
name = "dinner_generator_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
clap = { version = "4.5.17", features = ["derive"] }
eframe = "0.29.0"
egui = "0.29.0"
rand = "0.8.5"
